apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: devops-harbor
  namespace: default
spec:
  type: NodePort
  selector:
    app: harbor
    component: nginx
  ports:
  - name: http
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32443
    port: 443
    protocol: TCP
    targetPort: 8443
