apiVersion: v1
kind: Service
metadata:
  name: devops-redis-service
  labels:
    app: devops-redis
spec:
  type: NodePort
  selector:
    app: devops-redis
  ports:
    - name: devops-redis-port
      protocol: TCP
      port: 6379
      nodePort: 31852