apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  labels: 
    app: redmine
spec:
  type: NodePort
  selector:
    app: redmine
  ports:
    - name: ui
      protocol: TCP
      port: 3000
      nodePort: 32748
