apiVersion: v1
kind: Service
metadata:
  name: devopsdb-service
  labels: 
    app: devopsdb
spec:
  type: NodePort
  selector:
    app: devopsdb
  ports:
    - name: devopsdb-port
      protocol: TCP
      port: 5432
      nodePort: 31403
