apiVersion: v1
kind: Service
metadata:
  name: sonarqube-server-service
  labels:
    app: sonarqube-server
spec:
  type: NodePort
  selector:
    app: sonarqube-server
  ports:
    - name: apiport
      protocol: TCP
      port: 9000
      nodePort: 31910
