apiVersion: v1
kind: Service
metadata:
  name: devopsapi-service
  labels: 
    app: devopsapi
spec:
  type: NodePort
  selector:
    app: devopsapi
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 20
  ports:
    - name: devopsapi-port
      protocol: TCP
      port: 10009
      nodePort: 31850
