apiVersion: v1
kind: Service
metadata:
  name: harbor-service
  namespace: default
  labels:
    app: harbor
    component: portal
    release: harbor
spec:
  type: NodePort
  selector:
    app: harbor
    component: portal
    release: harbor
  ports:
    - name: harbor-port
      protocol: TCP
      port: 8443
      nodePort: 32443
